// <auto-generated />
using System;
using InvestorSystem.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestorSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220720083901__AddedUserSchema")]
    partial class _AddedUserSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestorSystem.DataModel.Table.Gender", b =>
                {
                    b.Property<string>("GenderCD")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenderCD");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderCD = "M",
                            Description = "Male",
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderCD = "F",
                            Description = "Female",
                            GenderName = "Female"
                        });
                });

            modelBuilder.Entity("InvestorSystem.DataModel.Table.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 7, 20, 8, 39, 1, 608, DateTimeKind.Utc).AddTicks(3037),
                            DisplayName = "Invester System",
                            IsDeleted = false,
                            Password = "InvSys@123",
                            UserEmail = "investor@system.com",
                            UserName = "Invester System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
